# Assets
ASSET_KEY = "assets/keyboard-enter.png"

# Main Menu
APP_TITLE = "EAY Generator"
EPISODE_NAME = "Episode Name"
EXAMPLE_EPISODE = "e.g. Inside Jokes"
CREATE_EPISODE = "Create New Episode"
EDIT_EPISODE = "Edit Selected Episode"
DELETE_EPISODE = "Delete Selected Episode"
REFRESH_LIST = "Refresh Episode List"
OPEN_FOLDER = "Open Episode Folder"
APPLY_EPISODES = "Apply Custom Episodes"

# Prompt Form / Editor
PERSONAL_PROMPT = "Personal Prompt"
PERSONAL_PROMPT_TIP = "(Required Field)\nThis is the question that will be asked to the player in question on their device at the start."
PERSONAL_PROMPT_EXAMPLE = "e.g. What is your favorite color?"
SCREEN_PROMPT = "Screen Prompt"
SCREEN_PROMPT_TIP = "(Required Field)\nThis is the question that will be shown to other players when coming up with lies, and will also be shown on screen alongside everyone's answers."
SCREEN_PROMPT_EXAMPLE = "e.g. <PLAYER>'s favorite color is <BLANK>."
ADD_PLAYER = "Insert Player Name into the Prompt"
ADD_PLAYER_TIP = "Inserts the <PLAYER> placeholder into the prompt, which will be replaced with the player's name when the prompt is displayed."
PLAYER_SYMBOL = "<PLAYER>"
ADD_BLANK = "Insert Blank into the Prompt"
ADD_BLANK_TIP = "Inserts the <BLANK> placeholder into the prompt, which will be replaced with a blank when the prompt is displayed."
BLANK_SYMBOL = "<BLANK>"
AUDIO_LOADED = "Audio loaded"
NO_AUDIO = "(No audio)"
ADD_AUDIO = "Set audio for current prompt (.ogg only)"
REMOVE_AUDIO = "Remove audio for current prompt"
SUGGESTIONS = "Suggestions"
SUGGESTIONS_TIP = "Dummy answers, used for Audience Lies in both games, as well as Jackbox Lies and Lie For Me button on Fibbage 4 only."
SUGGESTIONS_EXAMPLE = "e.g. chocolate"
REMOVE_SUGGESTION = "Remove Suggestion"
US_PROMPT = "Mark as U.S.-Centric Prompt"
US_PROMPT_TIP = "Check this box if the prompt is specific to U.S. culture, and should be removed when playing using the U.S. filter in compatible games."
NOT_FAMILY_PROMPT = "Mark as Not Family-Friendly Prompt"
NOT_FAMILY_PROMPT_TIP = "Check this box if the prompt is not family-friendly, and should be removed when playing using the Family-Friendly Filter in compatible games."
ADD_PROMPT = "Add Prompt"
PROMPT_EDITOR = "Prompt Editor"
UPDATE_AUDIOFILE = "update.ogg"
UPDATE_PROMPT = "Update Prompt"

# Prompt Table
HAS_AUDIO = "Audio?"
NOT_FAMILY_PROMPT_SHORT = "Family-Unfriendly?"
US_PROMPT_SHORT = "U.S.-Centric?"
EDIT = "Edit"
REMOVE = "Remove"
YES = "Yes"
NO = "No"

# Episode Editor
EPISODE_WINDOW = "EAY Generator - Episode: "
EPISODE = "Episode: "
SAVE_EPISODE = "Save Episode"
RETURN_TO_MENU = "Return to Main Menu"

# Build Menu
APP_TITLE_BUILD = "EAY Generator - Build Episode"
LINK_GAME_DESCRIPTION = "You need to choose a game pack to:\n - Include base prompts\n - Apply episodes directly into the game\n - Revert changes"
SELECT_PACK = "Select Party Pack Folder"
CHOOSE_GAME = "Choose game to set prompts on:"
FIBBAGE_3 = "Fibbage 3"
FIBBAGE_4 = "Fibbage 4"
INCLUDE_BASE_PROMPTS = "Include base game prompts"
SELECT_EPISODES = "Select episodes to include:"
GENERATE_ON_BUILD = "Generate Files On Build Folder"
GENERATE_ON_BUILD_TIP = "Generates the necessary files for the selected game in the build folder. You can then manually copy them to the game pack."
GENERATE_AND_INSTALL = "Generate And Install On Game Pack"
GENERATE_AND_INSTALL_TIP = "Generates the necessary files for the selected game and installs them directly into the linked game pack."
REVERT_CHANGES = "Revert Changes"
REVERT_CHANGES_TIP = "Reverts all changes made to the game pack by restoring the original files obtained from the backup."

# Dialog Box
SUCCESS = "Success"
WARNING = "Warning"
ERROR = "Error"
NO_PACK_MESSAGE = "No game pack linked for the selected game. Please link a game pack first."
NO_EPISODE_MESSAGE = "No episodes selected!"
INVALID_GAMEPACK_MESSAGE = "Invalid game pack directory selected."

# File Manager
SELECT_GAMEPACK = "Select the game pack directory"
SELECT_AUDIOFILE = "Select Audio File"
AUDIO_TYPE = "Audio Files (*.ogg)"